author_name: Test
border:
  color:
  - 255
  - 255
  - 255
  custom:
    bottom: 50
    left: 10
    right: 50
    top: 10
  fixed_ratio:
    a: 300
    auto_param: b
    b: 50
    c: 700
  preset: small
  use_custom: false
  use_fixed_ratio: true
exif:
  alignment: left
  author_name: Test Photographer
  enabled: true
  field_layout:
  - focal_length_35mm
  - aperture
  - iso
  - exposure_time
  fields:
  - focal_length_35mm
  - aperture
  - iso
  - exposure_time
  font_color:
  - 0
  - 0
  - 0
  font_family: Roboto Regular
  font_size: 100
  line_spacing: 80
  margin: 100
  position: bottom
input_dir: /home/scd/Downloads
logo_dir: ''
logos:
- enabled: true
  offset_x: 0
  offset_y: 0
  path: /home/scd/Downloads/Sony_Alpha_logo.svg
  position: bottom-left
  scale: 0.5
- enabled: false
  offset_x: 0
  offset_y: 0
  path: ''
  position: bottom-right
  scale: 0.5
- enabled: false
  offset_x: 0
  offset_y: 0
  path: ''
  position: top-left
  scale: 0.5
- enabled: false
  offset_x: 0
  offset_y: 0
  path: ''
  position: top-right
  scale: 0.5
output:
  format: JPEG
  jpeg_quality: 95
  suffix: _bordered
output_dir: /home/scd/Downloads
