author_name: 派大扔
border:
  color:
  - 255
  - 255
  - 255
  custom:
    bottom: 50
    left: 10
    right: 50
    top: 10
  preset: small
  use_custom: false
exif:
  alignment: left
  author_name: Test Photographer
  enabled: true
  fields:
  - body_serial_number
  - focal_length_35mm
  - iso
  - lens_model
  - software
  - white_balance
  font_color:
  - 0
  - 0
  - 0
  font_size: 24
  line_spacing: 4
  margin: 10
  position: bottom
input_dir: /home/scd/Downloads
logo_dir: ''
logos:
- enabled: false
  offset_x: 0
  offset_y: 0
  path: D:/ltq/PyBorderEXIF/Sony_Alpha_logo.svg
  position: bottom-left
  scale: 0.5
- enabled: false
  offset_x: 0
  offset_y: 0
  path: ''
  position: bottom-right
  scale: 0.5
- enabled: false
  offset_x: 0
  offset_y: 0
  path: ''
  position: top-left
  scale: 0.5
- enabled: false
  offset_x: 0
  offset_y: 0
  path: ''
  position: top-right
  scale: 0.5
output:
  format: JPEG
  jpeg_quality: 95
  suffix: _bordered
output_dir: /home/scd/Downloads
